# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### test
#POST http://192.168.0.156/auth/verify
POST http://47.91.219.7:2020/ordermanager/addContract
Content-Type: application/x-www-form-urlencoded

id=001&body=001&desc=test&token=BENJO112YUbdZHxsb[UWsEE

###